language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

sudo: false

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar update --prefer-stable

notifications:
  email:
    - payumsupport@forma-pro.com